### ISSUE TITLE
update the source

### ISSUE THREAD

**Issue by cutypie2351** [WzrterFX/cs2-fov-changer#1]
hi, i want to update your source, what is the offsets name i need to dump?
for example what the name of this offsets you added:
```
	uintptr_t fovAddr = 0x017E8150; // what is the offsets name?
	vector<DWORD> fovOffsets{ 0xD70 }; // what is the offsets name?
```

thank you @WzrterFX

**Comment by WzrterFX** [comment]
Hi, you can take the offsets that was dumped for you "https://github.com/a2x" - auto update offsets for cs2.

You must find your player in offsets.hpp "https://github.com/a2x/cs2-dumper/blob/main/generated/offsets.hpp line 26"
And find fov offset in client_dll.hpp "https://github.com/a2x/cs2-dumper/blob/main/generated/client.dll.hpp line 112"
```
// updated from cs2 dumper 13.11.2023
uintptr_t fovAddr = 0x17FCDB8; 
vector<DWORD> fovOffsets{ 0x6A4 }; 
```

Check new offset result in Cheat Engine
![image](https://github.com/WzrterFX/cs2-fov-changer/assets/122642787/2bb803a9-a2ee-4c1e-86ef-d25bbe4368f4)
![image](https://github.com/WzrterFX/cs2-fov-changer/assets/122642787/1ea630fb-d685-44da-80f5-af483ea6830d)

What about my addres, I didn't take them from "https://github.com/a2x"
I found them myself, just using the cheat engine ( offset not included from localPlayer )

**Comment by cutypie2351** [comment]
> Hi, you can take the offsets that was dumped for you "https://github.com/a2x" - auto update offsets for cs2.
> 
> You must find your player in offsets.hpp "https://github.com/a2x/cs2-dumper/blob/main/generated/offsets.hpp line 26" And find fov offset in client_dll.hpp "https://github.com/a2x/cs2-dumper/blob/main/generated/client.dll.hpp line 112"
> 
> ```
> // updated from cs2 dumper 13.11.2023
> uintptr_t fovAddr = 0x17FCDB8; 
> vector<DWORD> fovOffsets{ 0x6A4 }; 
> ```
> 
> Check new offset result in Cheat Engine ![image](https://user-images.githubusercontent.com/122642787/282568982-2bb803a9-a2ee-4c1e-86ef-d25bbe4368f4.png) ![image](https://user-images.githubusercontent.com/122642787/282568110-1ea630fb-d685-44da-80f5-af483ea6830d.png)
> 
> What about my addres, I didn't take them from "https://github.com/a2x" I found them myself, just using the cheat engine ( offset not included from localPlayer )

wow thank you,
but when i update the fox inside your source, the imgui slider changing the value * 100 times like its not wking corretly you can test, in cheat engine its work fine. and also do you know how can i change the localPlayerFov also? like the fov of myself player?
thank you for your answer

**Comment by WzrterFX** [comment]
You need a different offset that changes not only the camera ye, but i have not found this offset on cs2Dumper =(
